// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:b7c0f4d6-98b4-42c3-8fad-c75cd5475418',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_QT2tEzvxe',
  aws_user_pools_web_client_id: '1tvvl8acbi85i6m7hseqlboq1l',
  oauth: {
    domain:
      'amplifyteste4f02e2aa-4f02e2aa-test.auth.us-east-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: 'myapp://',
    redirectSignOut: 'myapp://',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_appsync_graphqlEndpoint:
    'https://wzmcotpaiveltcdlbcilchu5mu.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket:
    'amplifyteste41154c1604ac413989a097887f699ef9104442-test',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
