// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:32239a4c-1443-42fa-9bf1-c8c244c3a985',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_ufXes0Mxi',
  aws_user_pools_web_client_id: '5u42seq0ou8fipdbdpq3thea87',
  oauth: {
    domain: 'teste-diego-test.auth.us-east-1.amazoncognito.com',
    scope: [
      'phone',
      'email',
      'openid',
      'profile',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: 'myapp://',
    redirectSignOut: 'myapp://',
    responseType: 'code',
  },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_appsync_graphqlEndpoint:
    'https://wyz7d7zctjfwrijoceaju4znti.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: 'first-buckettest-test',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
