// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:32239a4c-1443-42fa-9bf1-c8c244c3a985',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_ufXes0Mxi',
  aws_user_pools_web_client_id: '5u42seq0ou8fipdbdpq3thea87',
  oauth: {
    domain: 'teste-diego-test.auth.us-east-1.amazoncognito.com',
    redirectSignIn: 'myapp://',
    redirectSignOut: 'myapp://',
    responseType: 'code',
  },
  aws_appsync_graphqlEndpoint:
    'https://wyz7d7zctjfwrijoceaju4znti.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsmobile;
